# Generated by Django 4.1.5 on 2023-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
