# Generated by Django 4.1.5 on 2023-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="detail",
            new_name="details",
        ),
    ]
